"""update user model

Revision ID: 72d1dfcc3d5f
Revises: 0646e0c66c35
Create Date: 2025-08-16 08:23:08.475150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d1dfcc3d5f'
down_revision: Union[str, Sequence[str], None] = '0646e0c66c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, default=sa.true()))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'name')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
